frase = 'Curso em Vídeo Python'
print(frase)
print(frase[3])
print(frase[9:14])
print(frase[9:])
print(frase[:5])
print(frase[::2])
print(frase.count('o'))
print(frase.count('O'))
print(frase.upper().count('O'))
print(frase.lower())
print(frase.upper())
print(frase.replace('Python', 'Android'))
print(frase.capitalize())
print(frase.find('em'))
print(frase.split())
dividido = frase.split()
print(dividido[2])
print(dividido[2][3])
print(len(frase))
